"""added currency for transport, skill and home models

Revision ID: 0c6acad02728
Revises: 54f2051c8890
Create Date: 2023-11-24 19:57:17.501820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6acad02728'
down_revision: Union[str, None] = '54f2051c8890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'home', 'currency', ['currency_id'], ['id'])
    op.add_column('skill', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'skill', 'currency', ['currency_id'], ['id'])
    op.add_column('transport', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transport', 'currency', ['currency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transport', type_='foreignkey')
    op.drop_column('transport', 'currency_id')
    op.drop_constraint(None, 'skill', type_='foreignkey')
    op.drop_column('skill', 'currency_id')
    op.drop_constraint(None, 'home', type_='foreignkey')
    op.drop_column('home', 'currency_id')
    # ### end Alembic commands ###
