"""updated player

Revision ID: 19b0e08cab4d
Revises: 3c1358addabe
Create Date: 2023-11-25 02:09:26.449058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b0e08cab4d'
down_revision: Union[str, None] = '3c1358addabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'alive',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('player', 'deadly_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'deadly_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player', 'alive',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
