"""added authority_benefit

Revision ID: 24635c479ec9
Revises: fdd5eda5e49d
Create Date: 2023-11-24 01:24:15.506924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24635c479ec9'
down_revision: Union[str, None] = 'fdd5eda5e49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leisure', sa.Column('authority_benefit_min', sa.Integer(), nullable=True))
    op.add_column('leisure', sa.Column('authority_benefit_max', sa.Integer(), nullable=True))
    op.add_column('street_action', sa.Column('authority_benefit_min', sa.Integer(), nullable=True))
    op.add_column('street_action', sa.Column('authority_benefit_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('street_action', 'authority_benefit_max')
    op.drop_column('street_action', 'authority_benefit_min')
    op.drop_column('leisure', 'authority_benefit_max')
    op.drop_column('leisure', 'authority_benefit_min')
    # ### end Alembic commands ###
