"""added description

Revision ID: 2d2db9c9aed9
Revises: e4de787dc207
Create Date: 2023-11-11 20:50:06.134159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2db9c9aed9'
down_revision: Union[str, None] = 'e4de787dc207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('description', sa.String(), nullable=True))
    op.add_column('food', sa.Column('description', sa.String(), nullable=True))
    op.add_column('health', sa.Column('description', sa.String(), nullable=True))
    op.add_column('home', sa.Column('description', sa.String(), nullable=True))
    op.add_column('leisure', sa.Column('description', sa.String(), nullable=True))
    op.add_column('skill', sa.Column('description', sa.String(), nullable=True))
    op.add_column('street_action', sa.Column('description', sa.String(), nullable=True))
    op.add_column('transport', sa.Column('description', sa.String(), nullable=True))
    op.add_column('work', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'description')
    op.drop_column('transport', 'description')
    op.drop_column('street_action', 'description')
    op.drop_column('skill', 'description')
    op.drop_column('leisure', 'description')
    op.drop_column('home', 'description')
    op.drop_column('health', 'description')
    op.drop_column('food', 'description')
    op.drop_column('business', 'description')
    # ### end Alembic commands ###
