"""updated player

Revision ID: 3c1358addabe
Revises: 0c6acad02728
Create Date: 2023-11-25 01:57:51.520244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1358addabe'
down_revision: Union[str, None] = '0c6acad02728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('alive', sa.Boolean(), nullable=True))
    op.add_column('player', sa.Column('deadly_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'deadly_days')
    op.drop_column('player', 'alive')
    # ### end Alembic commands ###
