"""updated models

Revision ID: 45e1bc04f768
Revises: 3402d1642cd6
Create Date: 2023-11-06 01:34:38.870550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e1bc04f768'
down_revision: Union[str, None] = '3402d1642cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_player',
    sa.Column('home_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['home.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('home_id', 'player_id')
    )
    op.create_index(op.f('ix_home_player_home_id'), 'home_player', ['home_id'], unique=False)
    op.create_table('skill_player',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_id', 'player_id')
    )
    op.create_index(op.f('ix_skill_player_skill_id'), 'skill_player', ['skill_id'], unique=False)
    op.create_table('transport_player',
    sa.Column('transport_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transport_id'], ['transport.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transport_id', 'player_id')
    )
    op.create_index(op.f('ix_transport_player_transport_id'), 'transport_player', ['transport_id'], unique=False)
    op.add_column('player', sa.Column('day', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'day')
    op.drop_index(op.f('ix_transport_player_transport_id'), table_name='transport_player')
    op.drop_table('transport_player')
    op.drop_index(op.f('ix_skill_player_skill_id'), table_name='skill_player')
    op.drop_table('skill_player')
    op.drop_index(op.f('ix_home_player_home_id'), table_name='home_player')
    op.drop_table('home_player')
    # ### end Alembic commands ###
