"""added exchange fields for models

Revision ID: 54c07392b6e1
Revises: 5fff062ebf39
Create Date: 2023-11-27 00:53:42.673817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c07392b6e1'
down_revision: Union[str, None] = '5fff062ebf39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('exchange_currency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'currency', 'currency', ['exchange_currency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currency', type_='foreignkey')
    op.drop_column('currency', 'exchange_currency_id')
    # ### end Alembic commands ###
