"""added income for food and health models

Revision ID: 54f2051c8890
Revises: 24635c479ec9
Create Date: 2023-11-24 02:00:53.266474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f2051c8890'
down_revision: Union[str, None] = '24635c479ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('income_min', sa.Integer(), nullable=True))
    op.add_column('food', sa.Column('income_max', sa.Integer(), nullable=True))
    op.add_column('health', sa.Column('income_min', sa.Integer(), nullable=True))
    op.add_column('health', sa.Column('income_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health', 'income_max')
    op.drop_column('health', 'income_min')
    op.drop_column('food', 'income_max')
    op.drop_column('food', 'income_min')
    # ### end Alembic commands ###
