"""added exchange fields for models

Revision ID: 5fff062ebf39
Revises: 19b0e08cab4d
Create Date: 2023-11-27 00:50:43.779461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fff062ebf39'
down_revision: Union[str, None] = '19b0e08cab4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('exchange_price', sa.Integer(), nullable=True))
    op.add_column('currency', sa.Column('exchange_price_min', sa.Integer(), nullable=True))
    op.add_column('currency', sa.Column('exchange_price_max', sa.Integer(), nullable=True))
    op.add_column('currency', sa.Column('exchange_change_step', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency', 'exchange_change_step')
    op.drop_column('currency', 'exchange_price_max')
    op.drop_column('currency', 'exchange_price_min')
    op.drop_column('balance', 'exchange_price')
    # ### end Alembic commands ###
