"""updated income

Revision ID: 79f9fa2efb84
Revises: 2d2db9c9aed9
Create Date: 2023-11-12 01:01:55.047687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f9fa2efb84'
down_revision: Union[str, None] = '2d2db9c9aed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('income_min', sa.Integer(), nullable=False))
    op.add_column('business', sa.Column('income_max', sa.Integer(), nullable=False))
    op.drop_column('business', 'income')
    op.add_column('street_action', sa.Column('income_min', sa.Integer(), nullable=False))
    op.add_column('street_action', sa.Column('income_max', sa.Integer(), nullable=False))
    op.drop_column('street_action', 'income')
    op.add_column('work', sa.Column('income_min', sa.Integer(), nullable=False))
    op.add_column('work', sa.Column('income_max', sa.Integer(), nullable=False))
    op.drop_column('work', 'income')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('income', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('work', 'income_max')
    op.drop_column('work', 'income_min')
    op.add_column('street_action', sa.Column('income', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('street_action', 'income_max')
    op.drop_column('street_action', 'income_min')
    op.add_column('business', sa.Column('income', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('business', 'income_max')
    op.drop_column('business', 'income_min')
    # ### end Alembic commands ###
