"""updated income

Revision ID: ef72fc92c47a
Revises: 79f9fa2efb84
Create Date: 2023-11-12 01:04:00.522410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef72fc92c47a'
down_revision: Union[str, None] = '79f9fa2efb84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('income', sa.Integer(), nullable=False))
    op.drop_column('business', 'income_min')
    op.drop_column('business', 'income_max')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('income_max', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('business', sa.Column('income_min', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('business', 'income')
    # ### end Alembic commands ###
