"""updated models

Revision ID: fdd5eda5e49d
Revises: ef72fc92c47a
Create Date: 2023-11-24 00:29:41.605865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd5eda5e49d'
down_revision: Union[str, None] = 'ef72fc92c47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('currency_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'food', 'currency', ['currency_id'], ['id'])
    op.add_column('health', sa.Column('currency_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'health', 'currency', ['currency_id'], ['id'])
    op.add_column('leisure', sa.Column('currency_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'leisure', 'currency', ['currency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leisure', type_='foreignkey')
    op.drop_column('leisure', 'currency_id')
    op.drop_constraint(None, 'health', type_='foreignkey')
    op.drop_column('health', 'currency_id')
    op.drop_constraint(None, 'food', type_='foreignkey')
    op.drop_column('food', 'currency_id')
    # ### end Alembic commands ###
