"""updated relations

Revision ID: ff48a8e1bd51
Revises: c0ec79934919
Create Date: 2023-11-06 02:26:24.997921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff48a8e1bd51'
down_revision: Union[str, None] = 'c0ec79934919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_player',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_id', 'player_id')
    )
    op.create_index(op.f('ix_business_player_business_id'), 'business_player', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_player_business_id'), table_name='business_player')
    op.drop_table('business_player')
    # ### end Alembic commands ###
